### ISSUE TITLE
SPRINT 2: Bedenk welke statistieken er nodig zijn voor het dashboard

### ISSUE THREAD

**Issue by Maartenlevi** [sfh0345/Steam-Project#15]

**Comment by SanderNeele** [comment]
1. Welke games spelen mijn vrienden: alle games die het meest zijn gespeeld door mijn vrienden
* Per vriend top 5 games op speeltijd 
1. Wanneer spelen mijn vrienden 
2. Deze game vind je misschien leuk: heb jij niet maar je vrienden wel

* Gemiddelde uur per dag gamen op steam
    * Kwantitatief 
* Speelgedrag per dag van de week 
    * Kwanitatief en kwalitatief
* Gemiddelde en maximale speeltijd per sessie
    * Kwanitatief 
* Populariteit van games genres per gebruiker
    * Kwalitatief
* Gemiddelde aantal achivements per gebruiker 
    * Kwantitatief
* Verhouding tussen en single en multiplayer games 
    * Kwantitatief en kwalitatief
* Percentage gebruik per game (10% game 1, 30% game 2)
