### ISSUE TITLE
PROG TI - Connectie tussen TI en PROG via serial ports

### ISSUE THREAD

**Issue by sfh0345** [sfh0345/Steam-Project#46]
code van pc naar pico:

https://github.com/HU-TI-DEV/v1oict-examples/tree/main/serial

wij hebben code nodig die ook van pico naar pc kan worden gestuurd

**Comment by Abdl2000** [comment]
Dit is reeds gerealiseerd.

**Comment by Abdl2000** [comment]
Deze connectie was nodig om het steamID te gebruiken voor het inloggen.
