### ISSUE TITLE
de lineaire regressie functie toepassen voor voorspellingen voor de user

### ISSUE THREAD

**Issue by Maartenlevi** [sfh0345/Steam-Project#69]

**Comment by Abdl2000** [comment]
Het algoritme is geschreven en getest door Maarten. Het berekent de verhouding tussen de beoordeling van het spel door gebruikers en de gemiddelde speeltijd. Een conclusie die we kunnen trekken uit de data is dat hoe langer de speeltijd, hoe hoger de beoordeling is. Dit komt doordat we redelijkerwijs kunnen voorspellen dat iemand die een spel lang speelt er plezier aan beleeft en dus waarschijnlijk een positievere beoordeling zal geven. Het blijft echter een gemiddelde, dus er zijn uitzonderingen waarin de beoordeling zelfs beter of lager is. Samen met Sander wordt nog nagedacht over een nuttige toepassing van dit algoritme in het dashboard.
